name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your main branch name

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "mandeepb29@gmail.com"
          git config --global user.name "mandeepb29"
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy Gatsby app
        run: npm run deploy:ci
          
